### PR TITLE
Process single-error responses from the Batch API

### LINKED ISSUE #86: Expand single error response from batch API endpoint into error responses for all events in batch
The event batch API endpoint that has only one failure response for the whole batch, not a collection of success/fail statuses. When these single-error-for-a-batch responses appear, log the situation at the DEBUG level.

### PR DESCRIPTION
**Pull request by robbkidd**
Fixes #86

### CODE REVIEW

File: lib/libhoney/client.rb [hunk 1]
```diff
@@ -51,13 +51,17 @@ class Client
...
+    #   how the types will be handled:
+    #     nil: (default, recommended)
+    #   Connection proxying will be determined from any +http_proxy+, +https_proxy+, and +no_proxy+ environment
+    #   variables set for the process.
+    #     String:
+    #   The value must be the URI for connecting to a forwarding web proxy. Must be parsable by stdlib URI.
+    #     Array: (deprecated, removal in v2.0)
+    #   The value must have one and at most four elements: e.g. +['host', port, 'username', 'password']+.
+    #   The assumption is that the TCP connection will be tunneled via HTTP, so the assumed scheme is +http://+.
+    #   +host+ is required. +port+ is optional (default:80), unless a +username+ is included. +password+ is optional.
```
Comment (robbkidd) [inline lib/libhoney/client.rb:64]: Uh. I'd been trying to make the layout of this RDoc less bad. Didn't mean to include it in this PR. I'll remove this.

File: test/libhoney_test.rb [hunk 2]
```diff
@@ -447,33 +487,113 @@ def test_json_error_handling
...
 
-      response = @honey.responses.pop
-      assert_equal(2, response.metadata)
-      assert_equal(202, response.status_code)
+      responses = []
+      while (response = @honey.responses.pop)
+        responses << response
+      end
+      assert_equal(event_count, responses.size, 'We have a response for each attempted event')
+      # assert_equal([], responses.map(&:metadata))
```
Comment (robbkidd) [inline test/libhoney_test.rb:577]: oops. I'll get rid of this.

File: lib/libhoney/transmission.rb [hunk 3]
```diff
@@ -190,15 +190,34 @@ def enqueue_response(response)
...
+        end
+      else
+        error = JSON.parse(http_response.body)['error']
+        if %w[debug trace].include?(ENV['LOG_LEVEL'])
+          warn "#{self.class.name}: error sending data to Honeycomb - #{http_response.status} #{error}"
+        end
+        batch.each do |batched_event|
+          next unless batched_event # skip nils enqueued from serialization errors
+
+          enqueue_response(
```
Comment (vreynolds) [inline lib/libhoney/transmission.rb:213]: minor nit: the two (create response)/enqueue branches are not symmetrical

**Review by vreynolds — APPROVED** [review]

**Comment by vreynolds** [comment]
Needs bump label

**Review by MikeGoldsmith — CHANGES_REQUESTED** [review]
@robbkidd - there's a couple of TODOs and feedback to fix up before we can merged this.

File: lib/libhoney/transmission.rb (hunk 3 above)
Comment (robbkidd) [reply lib/libhoney/transmission.rb:215]: Updated so that the two sides of the branch use `enqueue_response( Response.new( ... ) )` for more matchy matchy.

**Review by vreynolds — APPROVED** [review]
